/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Design a switch-led-buzzer system using stmlib and debouncing
   Case-1: If you press switch-1, led-1 and led-2 should glow together and at the same time buzzer should be on.
   Case-2: If you press switch-2, both led-1 and led-2 should be off and buzzer should also become off.
   Case-3: If you press switch-3, led-1, led-2 and led-3 should glow together and at the same time buzzer should be on.
   Case-4: If you press switch-4, all the led should be on and buzzer should become off. */

#include <stdint.h>
#include <stm32f405xx.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  //#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	//switch-1 led-1,2 buzzer
	RCC->AHB1ENR|=(1<<1);
	RCC->AHB1ENR|=(1<<2);
	GPIOC->MODER|=(1<<12);
	GPIOC->MODER&=~(1<<13);
	GPIOB->MODER|=(1<<26);
	GPIOB->MODER&=~(1<<27);
	GPIOC->MODER|=(1<<18);
	GPIOC->MODER&=~(1<<19);
	GPIOB->IDR&=~(3<<14);

	//switch-2
	GPIOB->IDR&=~(3<<6);

	//switch-3 led-3
	GPIOB->MODER|=(1<<28);
	GPIOB->MODER&=~(1<<29);
	GPIOB->IDR&=~(3<<8);

	//switch-4 led-4
	RCC->AHB1ENR|=(1<<0);
	GPIOB->MODER|=(1<<30);
	GPIOB->MODER&=~(1<<31);
	GPIOA->IDR&=~(3<<30);

	uint32_t current_state=0;
	uint32_t last_state=1;
	while(1)
	{
		current_state=(GPIOB->IDR>>7) & 1;
		if(current_state!=last_state)
		{
			current_state=(GPIOB->IDR>>7) & 1;
			if(current_state==0)
			{
				GPIOC->ODR&=~(1<<6); //led-1 on
				GPIOB->ODR&=~(1<<13);//LED-2 ON
				GPIOB->ODR|=(1<<14);
				GPIOB->ODR|=(1<<15);
				GPIOC->ODR|=(1<<9);//buzzer on
			}
			last_state=current_state;
		}

		current_state=(GPIOB->IDR>>7) & 1;
		if(current_state!=last_state)
		{
			current_state=(GPIOB->IDR>>7) & 1;
			if(current_state==0)
			{
				GPIOC->ODR|=(1<<6); //led-1 off
				GPIOB->ODR|=(1<<13);//LED-2 OFF
				GPIOB->ODR|=(1<<14);
				GPIOB->ODR|=(1<<15);
				GPIOC->ODR&=~(1<<9);//buzzer off*/
			}
			last_state=current_state;
		}
		current_state=(GPIOB->IDR>>3) & 1;
		if(current_state!=last_state)
		{
			current_state=(GPIOB->IDR>>3) & 1;
			if(current_state==0)
			{
				GPIOC->ODR|=(1<<6); //led-1 on
				GPIOB->ODR|=(1<<13);//LED-2 on
				GPIOB->ODR|=(1<<14);//led-3 off
				GPIOA->ODR|=(1<<15);//led-4 off
				GPIOC->ODR&=~(1<<9);//buzzer off*/
			}
			last_state=current_state;
		}

		current_state=(GPIOB->IDR>>3) & 1;
		if(current_state!=last_state)
		{
			current_state=(GPIOB->IDR>>3) & 1;
			if(current_state==0)
			{
				GPIOC->ODR|=(1<<6); //led-1 off
				GPIOB->ODR|=(1<<13);//LED-2 OFF
				GPIOB->ODR|=(1<<14);//led-3 off
				GPIOA->ODR|=(1<<15);//led-4 off
				GPIOC->ODR&=~(1<<9);//buzzer off*/
			}

			last_state=current_state;
		}

		current_state=(GPIOB->IDR>>4) & 1;
		if(current_state!=last_state)
		{
			current_state=(GPIOB->IDR>>4) & 1;
			if(current_state==0)
			{
				GPIOC->ODR&=~(1<<6); //led-1 on
				GPIOB->ODR&=~(1<<13);//LED-2 On
				GPIOB->ODR&=~(1<<14);//led-3 on
				GPIOA->ODR|=(1<<15);//led-4 off
				GPIOC->ODR|=(1<<9);//buzzer on*/
			}
			last_state=current_state;
		}
		current_state=(GPIOB->IDR>>4) & 1;
		if(current_state!=last_state)
		{
			current_state=(GPIOB->IDR>>4) & 1;
			if(current_state==0)
			{
						GPIOC->ODR|=(1<<6); //led-1 off
						GPIOB->ODR|=(1<<13);//LED-2 OFF
						GPIOB->ODR|=(1<<14);//led-3 off
						GPIOA->ODR|=(1<<15);//led-4 off
						GPIOC->ODR&=~(1<<9);//buzzer off*/
			}
			last_state=current_state;
		}

		current_state=(GPIOA->IDR>>15) & 1;
		if(current_state!=last_state)
		{
			current_state=(GPIOA->IDR>>15) & 1;
			if(current_state==0)
			{
				GPIOC->ODR&=~(1<<6); //led-1 on
				GPIOB->ODR&=~(1<<13);//LED-2 On
				GPIOB->ODR&=~(1<<14);//led-3 on*/
				GPIOB->ODR&=~(1<<15);//led-4 on
				GPIOC->ODR&=~(1<<9);//buzzer off
			}
			last_state=current_state;
		}

		current_state=(GPIOA->IDR>>15) & 1;
				if(current_state!=last_state)
				{
					current_state=(GPIOA->IDR>>15) & 1;
					if(current_state==0)
					{
						GPIOC->ODR|=(1<<6); //led-1 off
						GPIOB->ODR|=(1<<13);//LED-2 OFF
						GPIOB->ODR|=(1<<14);//led-3 off*/
						GPIOB->ODR|=(1<<15);//led-4 off
						GPIOC->ODR&=~(1<<9);//buzzer off
					}
					last_state=current_state;
				}
	}
	//for(;;);
}

