/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  //#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <STM32F405xx.h>
#include "lcd.h"

/*
uint32_t *rcc_ahb1enr=(uint32_t*)0x40023830;// for setting the bits
uint32_t *gpiob_moder = (uint32_t*)0x40020400;  // GPIOB mode register for switch
uint32_t *gpiob_idr = (uint32_t*)0x40020410; /// switch1 input data regsiter

int main(void)
{
	/* Loop forever

		*rcc_ahb1enr |= (1 << 1);  // port b

	// Clear bits
		//*gpiob_moder &=~(3<<14);// this clear 14th bits// switch as 00 bcz going for 00 will go 11 which is 3 switch
/*
lcd_gpio_init();
lcd_init();

while(1)
				{
                   uint8_t buttonstatus=(uint8_t)(*gpiob_idr &(1<<7));
                   if(buttonstatus==0)// switch active low pb7
                   { lcd(0x80, 0);        // Move cursor to the start of the first line
                   lcd_string("LCD ON"); // Display "LCD ON"
				}
                   else
                   {
                	   lcd(0x01, 0);        // Clear LCD
                   }


				}

} */
		//incrment switch on lcd ,sw2 decrement,sw 3 reset

		uint32_t *RCC_AHB1ENR = (uint32_t*)0x40023830;

		uint32_t *GPIOC_MODER = (uint32_t*)0x40020800;

		uint32_t *GPIOC_ODR = (uint32_t*)0x40020814;

		uint32_t *GPIOB_IDR = (uint32_t*)0x40020410;

		uint32_t *GPIOB_MODER = (uint32_t*)0x40020400;

		uint32_t *GPIOA_MODER = (uint32_t*)0x40020000;

		uint32_t *GPIOA_IDR = (uint32_t*)0x40020010;

		uint32_t *GPIOB_ODR = (uint32_t*)0x40020414;

		void switch_gpio_init(void) {

		    // Enable GPIOB clock

		    RCC->AHB1ENR |= (1 << 1);

		    // Configure PB7, PB3, PB4 as input (00 in MODER)

		    GPIOB->MODER &= ~(3 << 14); // PB7

		    GPIOB->MODER &= ~(3 << 6);  // PB3

		    GPIOB->MODER &= ~(3 << 8);  // PB4

		}

		void display_count(uint8_t count) {

		    lcd(0x80, 0);    // Move cursor to the first line

		    lcd_string("Count: "); // Print "Count: "

		    single_print(count); // Print the count value

		}

		int main(void) {

		    lcd_gpio_init();  // Initialize LCD GPIO

		    lcd_init();       // Initialize LCD

		    switch_gpio_init(); // Initialize switches

		    uint32_t count = 0; // Initialize counter

		    uint8_t lastButton1State = 1;

		    uint8_t lastButton2State = 1;

		    uint8_t lastButton3State = 1;

		    display_count(count); // Display initial count

		    while (1) {

		        // Read switch states

		        uint8_t button1State = ((GPIOB->IDR & (1 << 7)) == 0);

		        uint8_t button2State = ((GPIOB->IDR & (1 << 3)) == 0);

		        uint8_t button3State = ((GPIOB->IDR & (1 << 4)) == 0);

		        // Switch 1 (PB7) - Increase count

		        if (button1State == 0 && lastButton1State == 1) {

		            count++; // Increase count

		            display_count(count); // Update LCD

		        }

		        // Switch 2 (PB3) - Decrease count

		        if (button2State == 0 && lastButton2State == 1) {

		            if (count > 0) {

		                count--; // Decrease count

		                display_count(count); // Update LCD

		            }

		        }

		        // Switch 3 (PB4) - Reset count to 0

		        if (button3State == 0 && lastButton3State == 1) {

		            count = 0; // Reset count

		            display_count(count); // Update LCD

		        }

		        // Update last button states

		        lastButton1State = button1State;

		        lastButton2State = button2State;

		        lastButton3State = button3State;

		    }

		}


