/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// works like bulb glows led 1 pc6 and pb7

uint32_t *RCC_AHB1ENR = (uint32_t*)0x40023830;

uint32_t *GPIOC_MODER = (uint32_t*)0x40020800;//. GPIOC (LED) Configuration:

uint32_t *GPIOC_ODR = (uint32_t*)0x40020814;//. GPIOC (LED) Configuration: //offest added

uint32_t *GPIOB_IDR = (uint32_t*)0x40020410; // GPIOB (Switch) Configuration: //offeset added

uint32_t *GPIOB_MODER = (uint32_t*)0x40020400;// GPIOB (Switch) Configuration:


int main(void)

{

	*RCC_AHB1ENR |=(1<<2);//// Enable GPIOC clock (for LED)

	*RCC_AHB1ENR |=(1<<1);//// Enable GPIOB clock (for Switch)

	*GPIOC_MODER |=(1<<12);// Set PC6 to output mode

	*GPIOC_MODER &=~(1<<13);// Clear bit 13 to configure PC6 as output

	*GPIOB_MODER &=~(3<<14);// Set PB7 to input mode Clears bits 14 and 15

	int state=0;

	while(1)


	{	uint16_t button_press = (uint16_t)(*GPIOB_IDR &(1<<7))==0;// PB7 reads 0. Button Press Detection:

		if(button_press)

		state^=1; // Toggle the state (flip state between 0 and 1)

		{
		if(state== 1)
			*GPIOC_ODR &=~(1<<6); //LED ON
		else
			*GPIOC_ODR |=(1<<6); //LED OFF (turn on PC6)
		}
	}

}


