/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
 // #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <STM32F405xx.h>
#include "lcd.h"

uint32_t *rcc_ahb1enr=(uint32_t*)0x40023830;// for setting the bits
uint32_t *gpiob_moder = (uint32_t*)0x40020400;  // GPIOB mode register for switch1
uint32_t *gpiob_idr = (uint32_t*)0x40020410; /// switch1 input data regsiter

int main(void)
{


		*rcc_ahb1enr |= (1 << 1);  // port b clock

	// Clear bits
		*gpiob_moder &=~(3<<14);// this clear 14th bits// switch as 00 bcz going for 00 will go 11 which is 3 switch

lcd_gpio_init();
lcd_init();

while(1)
				{
                   uint8_t buttonstatus=(uint8_t)(*gpiob_idr &(1<<7));

                   if(buttonstatus==0)// switch active low pb7
                   { lcd(0x84, 0);        // Move cursor to the start of the first line
                   lcd_string("LCD ON"); // Display "LCD ON"
				}
                   else
                   {
                	   lcd(0x01, 0);        // Clear LCD
                   }


				}

}
