/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <STM32F405xx.h>

void pwm_enable(uint32_t val){
	TIM3->CR1 &=~(1<<0);// Disable Timer3
	TIM3->CCR4 = val; // Set Compare Register 4 value for PWM duty cycle
	TIM3->CR1 |=(1<<0); // Enable Timer3
}
void delay(int ms) {
    for (volatile int i = 0; i < ms * 4000; i++);
}
int main(void){
	RCC->AHB1ENR |= (1<<2); // Enable GPIOC Clock

	GPIOC->MODER &=~(3<<18); // Clear bits 18 and 19 (Pin 9 mode)
	GPIOC->MODER |= (2<<18); // Set Pin 9 to Alternate Function mode (AF2)

	GPIOC->AFR[1]&=~(0xF<<4); // Clear AF selection bits for Pin 9
	GPIOC->AFR[1]|= (2<<4); // Set AF2 (TIM3_CH4)

	RCC->APB1ENR |=(1<<1); // Enable Timer3 clock

	TIM3->PSC = 0; // No prescaler, running at system clock (16 MHz)
	TIM3->ARR = 1600-1;
	TIM3->CNT = 0;

	TIM3->CCMR2 &= ~(7 << 12); // Clear previous mode
	TIM3->CCMR2 |= (6 << 12); // Set PWM Mode 1

//	TIM3->CCR4 |= (1<<3);
	TIM3->CCER |= (1<<12);
	TIM3->CCER &=~(1<<13);
	TIM3->CR1 |= (1<<0);

	uint32_t val = 3000; // Set PWM to 3000
	while(1){
				pwm_enable(val);
				delay(100);

				pwm_enable(0);
				delay(10);

				pwm_enable(val/2);
				delay(90);

				pwm_enable(val);
				delay(80);

				pwm_enable(0);
				delay(10);

				pwm_enable(val/2);
				delay(60);

				pwm_enable(val);
				delay(50);

				pwm_enable(0);
				delay(10);

				pwm_enable(val/2);
				delay(40);

				pwm_enable(val);
				delay(30);

				pwm_enable(val/2);
				delay(20);
	}
}
