/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <STM32F405xx.h>
#include "lcd.h"

int main(void)
{
lcd_gpio_init();
lcd_init();
lcd(0x80,0);
lcd('s',1);
lcd(0xc0,0);
lcd_string("embedded c");
while(1);

}



