/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"  // CMSIS header for STM32F4xx
#include <stdint.h>

// TIMER2 TIM2 used led for using timer to switch on off


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
 // #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//TIM2 Register Values

void delay_timer2(uint32_t n)
{
	for(uint32_t i=0; i<n ; i++)
	{
		while(!(TIM2->SR & (1<<0)));
	//while till timer overflows
	 // Timer running = bit 0=0, (0&1) =0,
	 //           !0=1(wait on while loop
		TIM2->SR &= 0; // Clearing bit 0
	}
}

int main(void)
{
	RCC->AHB1ENR |= (1<<2); // GPIO Enable, Bit 2 of AHB1ENR
	RCC->APB1ENR |= (1<<0); // Enabled TIM2, setting the bit 0

	GPIOC->MODER &=~(3<<12); // GPIOC pin12,13 clearing : 00 ->13 12
	GPIOC->MODER |= (1<<12); // 01 output mode, PC13=0, PC12=1

	//Configuring TIM2 Registers to produce delay
	// Here System Clock is 16MHz
	TIM2->PSC = 16000-1; // 16 000 000 000/16000 = 10 000
	TIM2->ARR =  1000-1; //10 000/10 000 = 1Hz

	//1Hz FREQ., IS TIME PERIOD ->UPDATE EVENT CAN HAPPEN
	TIM2->CNT  = 0;      // Clearing the CNT register
	TIM2->CR1 |=(1<<0);  // SET BIT 0 TO EABLE TIMER/COUNTER

	while(1)
	{
		delay_timer2(1);
		GPIOC->ODR ^= (1<<6);
	}
}



