/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


// turn on led 1 with sw1


uint32_t *rcc_ahb1enr=(uint32_t*)0x40023830;// for setting the bits
uint32_t *gpioc_moder = (uint32_t*)0x40020800; //mode register initial address led gpioc
uint32_t *gpiob_moder = (uint32_t*)0x40020400;  // GPIOB mode register for switch
uint32_t *gpioc_odr = (uint32_t*)0x40020814;//o/p data register led
uint32_t *gpiob_idr = (uint32_t*)0x40020410; /// switch1 input data regsiter

int main(void)
{
	/* Loop forever */
	*rcc_ahb1enr |= (1 << 2);  // Enable GPIOB clock necessary port c
	*rcc_ahb1enr |= (1 << 1);  // port b

	*gpioc_moder|=(1<<12);//set bit 1
	*gpioc_moder &=~(1<<13);//set bit 13 to 0 led


// Clear bits
	*gpiob_moder &=~(3<<14);// this clear 14th bits// switch as 00 bcz going for 00 will go 11 which is 3 switch

// or *gpioc_moder &= ~(1<< 14) and *gpioc_moder &= ~(1<< 15)

				while(1)
				{
                   uint8_t buttonstatus=(uint8_t)(*gpiob_idr &(1<<7));
                   if(buttonstatus==0)// switch active low pb7
					*gpioc_odr&=~(1<<6);//led on
                   else
                	   *gpioc_odr|=(1<<6);//led on


				}
}
