/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

    uint32_t *rcc_ahb1enr=(uint32_t*)0x40023830;// for setting the rcc
	uint32_t *gpioc_moder = (uint32_t*)0x40020800; //mode register initial address led gpioc for led1
	uint32_t *gpioc_odr = (uint32_t*)0x40020814;//o/p data register led1

	uint32_t *gpiob_moder = (uint32_t*)0x40020400;  // GPIOB mode register for switch this could be for switch 1,2,3??
	uint32_t *gpiob_idr = (uint32_t*)0x40020410; /// switch1 input
	uint32_t *gpiob_odr = (uint32_t*)0x40020414; //

int main(void)
{
	*rcc_ahb1enr |= (1 << 2);  // Enable GPIOB clock necessary port c
	*rcc_ahb1enr |= (1 << 1);  // port b

	*gpioc_moder|=(1<<12);//set bit 1
	*gpioc_moder &=~(1<<13);//set bit 13 to 0 led
	// Clear bits
	*gpiob_moder &=~(3<<14);// this clear 14th bits// switch as 00 bcz going for 00 will go 11 which is 3 switch

	while(1)
	{
		/ Read the switch state (PB7)
		        current_button_state = (*gpiob_idr & (1 << 7)) >> 7;

		        // Check if the button was just pressed (falling edge detection)
		        if (current_button_state == 0 && previous_button_state == 1)
		        {
		            // Debouncing: wait for a small delay to avoid multiple triggers
		            debounce_delay = 100000;
		            while (debounce_delay--);

		            // Toggle LED state
		            led_state = !led_state;

		            // Update the LED output based on the state
		            if (led_state)
		            {
		                *gpioc_odr |= (1 << 13);  // Turn on the LED (PC13)
		            }
		            else
		            {
		                *gpioc_odr &= ~(1 << 13); // Turn off the LED (PC13)
		            }
		        }

		        // Update the previous button state for next iteration
		        previous_button_state = current_button_state;
		    }

	}

}
