/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  //#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


// for enabling reset and clock
uint32_t *rcc_ahb1enr=(uint32_t*)0x40023830;// for setting the rcc
uint32_t *gpioc_moder = (uint32_t*)0x40020800; //mode register initial address led gpioc for led1
uint32_t *gpioc_odr = (uint32_t*)0x40020814;//o/p data register led
//for led1 & switch 1

uint32_t *gpiob_moder = (uint32_t*)0x40020400;  // GPIOB mode register for switch this could be for switch 1,2,3??
uint32_t *gpiob_idr = (uint32_t*)0x40020410; /// switch1 input data regsiter for led 1,2,3?

// for enabling led 2& 3 and switch 2&3 use gpiob p3,p4
uint32_t *gpiob_odr = (uint32_t*)0x40020414; //
//uint32_t *gpiob_moder= (uint32_t*)0x40020400;// for led 2
//uint32_t *gpiob_moder_switch = (uint32_t*)0x40020400;

//uint32_t *gpiob_idr = (uint32_t*)0x40020410; /// switch1 input data regsiter

// for led 4 and switch 4
//uint32_t *gpiob_moder_led = (uint32_t*)0x40020400;  // GPIOB mode register
uint32_t *gpioa_moder =(uint32_t*)0x40020000;  // GPIOA mode register pa15 switch 4
//uint32_t *gpiob_moder_switch = (uint32_t*)0x40020400;  // GPIOB mode register for p7,p3 and p4 switch 1,2,3
//uint32_t *gpiob_odr = (uint32_t*)0x40020414;// for led 2,3,4
uint32_t *gpioa_idr = (uint32_t*)0x40020010; /// switch4(p15) input data regsiter for gpioa pin switch 4
//uint32_t *gpiob_idr = (uint32_t*)0x40020410; /// switch1,2,3 input data regsiter

int main(void)
{
	//switch 1 and led 1
	*rcc_ahb1enr |= (1 << 2);  // Enable GPIOB clock necessary port c
		*rcc_ahb1enr |= (1 << 1);  // port b

		*gpioc_moder|=(1<<12);//set bit 1
		*gpioc_moder &=~(1<<13);//set bit 13 to 0 led


	// Clear bits
		*gpiob_moder &=~(3<<14);// this clear 14th bits//

	//	switch 2 and 3 and led 2 and 3
		// Set bits 26 and 27 to 01 for output mode
		*gpiob_moder |=(1<< 26);
		*gpiob_moder &=~(1<< 27);

				// Clear bits 28 and 29 to 00
				*gpiob_moder &= ~(1<< 29);  // This clears both bits 26 and 27 for PB13

						// Set bits 28 and 29 to 01 for output mode
				*gpiob_moder |= (1<< 28);




				*gpiob_moder &=~(3<< 6);// this clear 6th bits// switch as 00 bcz going for 00 will go 11 which is 3
				*gpiob_moder &=~(3<< 8);// this clear 8th bits// switch as 00 bcz going for 00 will go 11 which is 3


				//switch 4 and led 4
				*rcc_ahb1enr |= (1 << 0);  // port b pa15 a is 0 for switch


				*gpiob_moder|=(1<< 30);  // This sets

				*gpiob_moder &=~(1<< 31);
				*gpioa_moder &=~(3<<30);

								while(1)
									      	{
									                   uint32_t buttonstatus1=(uint32_t)(*gpiob_idr &(1<<7));
									                   uint32_t buttonstatus2=(uint32_t)(*gpiob_idr &(1<<3));
									                   uint32_t buttonstatus3=(uint32_t)(*gpiob_idr &(1<<4));
									                   uint16_t buttonstatus4=(uint16_t)(*gpioa_idr &(1<<15));

									                   if(buttonstatus1 == 0)// switch active low pb7
														{
									                	   *gpioc_odr&=~(1<<6);


														}
									                   else
									                   {

									                	   *gpioc_odr|=(1<<6);//led on

									                   }


									                   if(buttonstatus2==0)
									                   {
									                	   *gpiob_odr &=~(1<<13);//led on
									                   }
									                   else
									                   {
									                	   *gpiob_odr|=(1<<13);//led off
									                   }

									                   if(buttonstatus3 == 0)
									                   {
									                	   *gpiob_odr &=~(1 << 14); //set pb13
									                   }

									                   else
													   {
									                	   *gpiob_odr|=(1<<14);//led off
													   }

									                   if(buttonstatus4==0)
									                   {
									                	   *gpiob_odr &=~(1<<15);//led on
									                   }

									                   else{

									                       *gpiob_odr |=(1<<15);//led off

									                	   }
													}
}
