/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//led_pwm_timer pc6 led work for timer

#include <stdint.h>
#include <stm32f4xx.h>  // CMSIS header for STM32F4xx



uint32_t val=1000;

void pwm_enable(uint32_t val)

{   TIM3->CR1 &=~(1<<0);  // SET BIT 0 TO  disable timer
	TIM3->CCR1= val;
	TIM3->CR1 |=(1<<0);  // SET BIT 0 TO EnABLE TIMER

}

int main(void)
{
	RCC->AHB1ENR |= (1<<2); // GPIOC Enable, Bit 2 of AHB1ENR port b
	RCC->APB1ENR |= (1<<1); // Enabled TIM3 as timer3 on 1
	GPIOC->MODER &=~(1<<12); // GPIOC pin12,13 clearing : 00 ->13 12
	GPIOC->MODER |= (1<<13); // 10 alternatte fn output led on moder 12,13


RCC->AHB1ENR |= (1<<2); // GPIO Enable, Bit 2 of AHB1ENR port b
RCC->APB1ENR |= (1<<1); // Enabled TIM3 as timer3 on 1
GPIOC->MODER &=~(1<<12); // GPIOC pin12,13 clearing : 00 ->13 12
GPIOC->MODER |= (1<<13); // 10 alternatte fn output led on moder 12,13

TIM3->PSC = 0; // 16 000 000 000/16000 = 10 000
TIM3->ARR =  1600-1; // autoreload register
TIM3->CNT  = 0;      // Clearing the CNT register




// low for 0 to 6 / alternate function pC6 bcz af1 0010 (27,26,25,24) PG 286
		GPIOC->AFR[0] &= ~(1 << 24);
		GPIOC->AFR[0] &= ~(1 << 26);
		GPIOC->AFR[0] &= ~(1 << 27);
		GPIOC->AFR[0] |= (1 << 25);


		TIM3->CCMR1 &= ~(1 << 4); // (6,5,4)=110 PWM MODE 1 pg 636 oc1m
		TIM3->CCMR1 |= (1 << 5);
		TIM3->CCMR1 |= (1 << 6);

		TIM3->CCMR1 |= (1<<3); //SET BIT 3 as 1 oc1pe(preload register)
		TIM3->CCER |=(1<<0);//SET CC1E bit 0 to  1 pg641 cr1 hai
		TIM3->CR1 |=(1<<0);// set bit 0 CLOCK TIMER ENABLE



		while(1)
			{
			pwm_enable(val);


							for(uint32_t i=0;i<3000000;i++);

							pwm_enable(0.6*val);

							for(uint32_t i=0;i<3000000;i++);

							pwm_enable(0.3*val);

							for(uint32_t i=0;i<3000000;i++);

							pwm_enable(0.1*val);

							for(uint32_t i=0;i<300000;i++);
			}



}
