/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t *rcc_ahb1enr=(uint32_t*)0x40023830;// for setting the bits
uint32_t *gpioc_moder = (uint32_t*)0x40020800; //mode register initial address
uint32_t *gpioc_odr = (uint32_t*)0x40020814;//o/p data register


int main(void)
{
	/* Loop forever */
			  *rcc_ahb1enr |= (1 << 2);  // Enable GPIOB clock necessary

			// Clear bits
			*gpioc_moder &= ~(1<< 18);  // This clears both bits moder 9 bcz pc9 so 18,19th bits
			// Set bits
			*gpioc_moder |= (1<< 19);


			while(1)
			{

				*gpioc_odr &= ~(1 << 9); //set PC9  to low
				for(unsigned int i=0;i<100000;i++);
				*gpioc_odr |= (1 << 9); //off
				for(unsigned int i=0;i<100000;i++);


			}
}
