/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t *rcc_ahb1enr=(uint32_t*)0x40023830;// for setting the bits
uint32_t *gpiob_moder_led = (uint32_t*)0x40020400;  // GPIOB mode register
uint32_t *gpioa_moder_switch = (uint32_t*)0x40020000;  // GPIOB mode register
uint32_t *gpiob_odr = (uint32_t*)0x40020414;
uint32_t *gpioa_idr = (uint32_t*)0x40020010; /// switch1 input data regsiter 10


int main(void)
{
	*rcc_ahb1enr |= (1 << 1);  // port b for led
	*rcc_ahb1enr |= (1 << 0);  // port b pa15 a is 0 for switch

				*gpiob_moder_led |=(1<< 30);  // This sets

				*gpiob_moder_led &=~(1<< 31);
				*gpioa_moder_switch&=~(3<<30);
				while(1)
				{


				      uint16_t buttonstatus4=(uint16_t)(*gpioa_idr &(1<<15));

					  if(buttonstatus4 == 0)// switch active low pb7
						{
					                	   *gpiob_odr &=~(1<<15);//led on

										}


					                   else{
					                	   *gpiob_odr |=(1<<15);//led off

					                	   }
				}
}
