/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

uint32_t volatile *NVICIRQ_En = (uint32_t *)0xE000E100;

uint32_t *RCC_AHB1ENR = (uint32_t*)0x40023830; // RCC AHB1 Clock Enable Register
uint32_t *RCC_APB2ENR = (uint32_t*)0x40023844; // RCC APB2 Clock Enable Register for Timer1
uint32_t *GPIOB_MODER = (uint32_t*)0x40020400; // GPIOB Mode Register (Switches and LEDs)
uint32_t *GPIOB_ODR = (uint32_t*)0x40020414;   // GPIOB Output Data Register (Control LEDs)
uint32_t *TIM1_PSC = (uint32_t*)0x40010028;    // Timer1 Prescaler Register
uint32_t *TIM1_ARR = (uint32_t*)0x4001002C;    // Timer1 Auto-Reload Register pg 642
uint32_t *TIM1_CR1 = (uint32_t*)0x40010000;    // Timer1 Control Register 1
uint32_t *TIM1_SR =  (uint32_t*)0x40010010;     // Timer1 Status Register
uint32_t *TIM1_DIER = (uint32_t*)0x4001000C;   // Timer1 DMA/Interrupt Enable Register

void TIM1_UP_TIM10_IRQHandler(void);

int main(void)
{
	// Enable GPIOB clock for button input
	    *RCC_AHB1ENR |= (1<<1);

	    // Enable Timer 1 clock on APB1 from page 187 timer 1 bit 0
	    	*RCC_APB2ENR |= (1<<0);

	    // Configure PB13, PB14, PB15 as Outputs for LEDs
	        *GPIOB_MODER |= (1 << 26);   // Set PB13 as output
	        *GPIOB_MODER &= ~(1 << 27);  // Clear bit 27


	 // Configure Timer 1 with a 1 ms tick using 16 MHz clock
	        *TIM1_PSC = 16000-1;  // Prescaler
	        *TIM1_ARR = 1000;     // Auto-reload for 1 second



	              // Enable Timer 1 Update Interrupt
	              *TIM1_DIER |= (1 << 0);

	              *NVICIRQ_En |= (1 << 25); // Enable TIM1 IRQ in NVIC (IRQ) page 373

	              // Start Timer 1
	              *TIM1_CR1 |= (1 << 0);

	    	while(1);
}

/// Timer 1 Interrupt Service Routine (ISR)
void TIM1_UP_TIM10_IRQHandler(void)

{ *TIM1_SR &=~(1<<0);//clear UIF
*GPIOB_ODR ^= (1<<13); //toggle led
}
