/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>

uint32_t *rcc_ahb1enr=(uint32_t*)0x40023830;// for setting the bits
uint32_t *gpioc_moder = (uint32_t*)0x40020800; //mode register initial address
uint32_t *gpioc_odr = (uint32_t*)0x40020814;//o/p data register
uint32_t *gpiob_moder = (uint32_t*)0x40020400;  // GPIOB mode register
uint32_t *gpiob_odr = (uint32_t*)0x40020414;

int main(void)
{
    /* Loop forever */
	*rcc_ahb1enr|=(1<<2);// enable gpioc clock
	  *rcc_ahb1enr |= (1 << 1);  // Enable GPIOB clock necessary
	*gpioc_moder|=(1<<12);//set bit 12 to 1
	*gpioc_moder &=~(1<<13);//set bit 13 to 0

	// Clear bits 26 and 27 to 00
	*gpiob_moder &= ~(1<< 26);  // This clears both bits 26 and 27 for PB13

	// Set bits 26 and 27 to 01 for output mode
	*gpiob_moder |= (1<< 27);


	while(1)
	{
		*gpioc_odr=~(1<<6);//sets 6th bit to 0
		*gpioc_odr &= ~(1 << 13); //set pb13 to low
		for(unsigned int i=0;i<100000;i++);
		*gpioc_odr|=(1<<6);//off
		*gpioc_odr |= (1 << 13); //off
		for(unsigned int i=0;i<100000;i++);


	}
}

// ALTRERNATE WAYS
/*#include<stm32f405xx.h>
#include<stdint.h>

int main(void)
{

	RCC->AHB1ENR |=(1<<1);



	GPIOB->MODER &=~(1<<27);
	GPIOB->MODER |=(1<<26);


while(1)
	{


	GPIOB->ODR &=~(1<<13);
	for(unsigned int i=0;i<1000000;i++);

	GPIOB->ODR |=(1<<13);
	for(unsigned int i=0;i<1000000;i++);



	}

}*/
