/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// switch 1 & 2 led 1
uint32_t *RCC_AHB1ENR = (uint32_t*)0x40023830;

uint32_t *GPIOB_MODER = (uint32_t*)0x40020400;

uint32_t *GPIOB_IDR = (uint32_t*)0x40020410;

uint32_t *GPIOC_MODER = (uint32_t*)0x40020800;

uint32_t *GPIOC_ODR = (uint32_t*)0x40020814;



int main(void)

{

    *RCC_AHB1ENR |= (1 << 2); // Enable clock for GPIOC

    *RCC_AHB1ENR |= (1 << 1); // Enable clock for GPIOB

    // Configure PC6 as output (LED)

    *GPIOC_MODER |= (1 << 12); // Set bit 12 to 1 (output mode for PC6)

    *GPIOC_MODER &= ~(1 << 13); // Set bit 13 to 0 (output mode for PC6)

    // Configure PB7 as input (Switch)

    *GPIOB_MODER &= ~(3 << 14); // Clear bits for PB7 (input mode)

    // Configure PB3 as input (Switch 2 - to turn off LED 1)
    *GPIOB_MODER &= ~(3 << 6);   // Set PB3 as input (clear bits 6 and 7)




    uint8_t ledState = 0; // Variable to track the LED state (0 = off, 1 = on)

    uint8_t lastButtonState = 1; // Variable to detect button press (1 = not pressed, 0 = pressed)
    uint8_t lastButtonState1 = 1;




    while(1)

    {

        // Read the button status (Switch 1)

        uint8_t buttonStatus = (uint8_t)(*GPIOB_IDR & (1 << 7)) == 0; // Button pressed when PB7 is low
        // Read the button status for Switch 2 (PB3)
         uint8_t buttonStatus1 = (uint8_t)(*GPIOB_IDR & (1 << 3)) == 0; // Button pressed when PB3 is low

        if (buttonStatus == 0 && lastButtonState == 1) // Detect button press (falling edge)

        {


                *GPIOC_ODR &= ~(1 << 6); // Turn LED on (set PC6 low)

                ledState = 1; // LED is on
        }



               if (buttonStatus1 == 0 && lastButtonState1 == 1) // Detect button press (falling edge)

               {



                       *GPIOC_ODR |= (1 << 6); // Turn LED off (set PC6 high)


                       ledState = 0; // LED is on


               }

               lastButtonState = buttonStatus; // Update the last button state
               lastButtonState1 = buttonStatus1; // Update the last button state




    }

}
