/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f4xx.h>  // CMSIS header for STM32F4xx
#include <stdint.h>


int main(void)
{
	RCC->AHB1ENR |= (1<<1) | (1<<0); // Enable GPIOB an A
	RCC->AHB1ENR |= (1<<2); //GPIOA

	// Configure PC6, PB13, PB14, PB15 as outputs (LED1, LED2, LED3, LED4)
		GPIOC->MODER &=~(3<<12);
		GPIOC->MODER |= (1<<12); // PC6

		GPIOB->MODER &=~((1<<27) | (1<<29) | (1<<31));
		GPIOB->MODER |= ((1<<26) | (1<<28) | (1<<30)); // PB13, PB14, PB15

		// Configure PB7, PB3, PB4 as inputs (Switch1, Switch2, Switch3)
		GPIOB->MODER &=~((3<<6) | (3<<8) | (3<<14));


	// Configure PA15 as input (Switch4)
		GPIOA->MODER &=~(3<<30);

	RCC->APB2ENR |= (1<<14); // Enable SYSCFG for EXTI configuration

	//SYSCGG EXTIRCR PG 291 BCZ SWITCH 1 IS PB 7 SO BIT IS PB0001 SO register 2
	SYSCFG->EXTICR[1]|= (1<<12);
	SYSCFG->EXTICR[1]&= ~(1<<13);
	SYSCFG->EXTICR[1]&=~(1<<14);
	SYSCFG->EXTICR[1]&=	~(1<<15);

	//switch 2 pb 3 so register 1
	    SYSCFG->EXTICR[0] &=~(1<<15); //pg 291
		SYSCFG->EXTICR[0] &=~(1<<14);
		SYSCFG->EXTICR[0] &=~(1<<13);
		SYSCFG->EXTICR[0] |=(1<<12); // Set to GPIOB for EXTI3

		//SWITCH 3 ON PB4 regiter 2
		SYSCFG->EXTICR[1]|= (1<<0);
			SYSCFG->EXTICR[1]&= ~(1<<1);
			SYSCFG->EXTICR[1]&=~(1<<2);
			SYSCFG->EXTICR[1]&=	~(1<<3);

		//SYSCGG EXTIRCR PG 291 BCZ SWITCH 4 IS PA 15 SO BIT IS PA 0000 regiter 4 enure that its port A
		SYSCFG->EXTICR[3] &= ~(1<<15);
		SYSCFG->EXTICR[3] &= ~(1<<14);
		SYSCFG->EXTICR[3] &=~(1<<13);
		SYSCFG->EXTICR[3] &=(1<<12);

	// Enable rising edge trigger for Switch1, Switch2, Switch3, Switch4  Interrupt Mask Register.

		//When a bit in the IMR is set to 1, the corresponding external interrupt is unmasked(enabled)
		// and can generate an interrupt request (IRQ) to the NVIC (Nested Vector Interrupt Controller)

	EXTI->RTSR |= ((1<<7) | (1<<3) | (1<<4) | (1<<15));//Enables interrupt for Switch 1 (PB7)
	EXTI->IMR |= ((1<<7) | (1<<3) | (1<<4) | (1<<15));

	// Enable EXTI interrupts in NVIC // see vector table pg 377 for stm32f405
		NVIC_EnableIRQ(EXTI3_IRQn);
		NVIC_EnableIRQ(EXTI4_IRQn);
		NVIC_EnableIRQ(EXTI9_5_IRQn);
		NVIC_EnableIRQ(EXTI15_10_IRQn);

	while(1);
}



// Interrupt Handlers for EXTI3, EXTI4, EXTI9_5, and EXTI15_10 penf=ding register
void EXTI3_IRQHandler()
{
	if (EXTI->PR & (1 << 3))
	{
		GPIOB->ODR ^= (1 << 13); // Toggle LED2 (PB13)
		for(unsigned int i = 0; i < 10000; i++);
		EXTI->PR |= (1 << 3); // Clear pending bit
	}
}

void EXTI4_IRQHandler()
{
	if (EXTI->PR & (1 << 4))
	{
		GPIOB->ODR ^= (1 << 14); // Toggle LED3 (PB14)
		for(unsigned int i = 0; i < 10000; i++);
		EXTI->PR |= (1 << 4); // Clear pending bit
	}
}

void EXTI9_5_IRQHandler()
{
	if (EXTI->PR & (1 << 7))
	{
		GPIOC->ODR ^= (1 << 6); // Toggle LED1 (Pc6)
		for(unsigned int i = 0; i < 10000; i++);
		EXTI->PR |= (1 << 7); // Clear pending bit
	}
	if (EXTI->PR & (1 << 3))
	{
		GPIOB->ODR ^= (1 << 13); // Toggle LED2 (PB13)
		for(unsigned int i = 0; i < 10000; i++);
		EXTI->PR |= (1 << 3); // Clear pending bit
	}
}

void EXTI15_10_IRQHandler() //pg 374
{
	if (EXTI->PR & (1 << 15))
	{
		GPIOB->ODR ^= (1 << 15); // Toggle LED4 (PB15)
		for(unsigned int i = 0; i < 10000; i++);
		EXTI->PR |= (1 << 15); // Clear pending bit
	}
}

