/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <STM32F405xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  //#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



int main(void)
{   // Enable GPIOC and TIM3
    RCC->AHB1ENR |= (1 << 2); // GPIOC Enable
    RCC->APB1ENR |= (1 << 1); // TIM3 Enable

    GPIOC->AFR[0] &= ~(1 << 24);
    GPIOC->AFR[0] &= ~(1 << 26);
    GPIOC->AFR[0] &= ~(1 << 27);
    GPIOC->AFR[0] |= (1 << 25);

    GPIOC->MODER &=~(1<<12); // GPIOC pin12,13 clearing : 00 ->13 12
    GPIOC->MODER |= (1<<13); // 10 alternate fn output led on moder 12,13


    //timer 3 toggle mode
    	        TIM3->PSC = 16000-1; // 16 000 000 000/16000 = 10 000
    	    	TIM3->ARR =  6000-1; // auto reload register
    	    	TIM3->CCMR1 |= (1 << 4); // (6,5,4)=011 PWM MODE 1 pg 636 oc1m
    	    	TIM3->CCMR1 |= (1 << 5);
    	    	TIM3->CCMR1 &= ~(1 << 6);
    	    	TIM3->CNT  = 0;

    	    	TIM3->CCER |=(1<<0);// SET bit 0 as 1
    	    	TIM3->CR1 |=(1<<0);// SET bit 0 to 1

    	    	while (1) {

    	    		TIM3->CCR1=2000;//active low led work

    	    		while (!(TIM3->SR & (1 << 1)));// nothing matches so 0 bit 1 changing to 1

    	    		TIM3->SR &=~(1<<1); // Clearing bit 0

    	    		TIM3->CCR1=4000;
    	    		while (!(TIM3->SR & (1 << 1)));


    	    	}
}
