/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <STM32f405xx.h>
#include <lcd.h>

void counter_init()
{
	GPIOA->MODER |= (1<<31);     //PA15 --> SW4  enable Alternate Function mode
	GPIOA->MODER &=~(1<<30);

	GPIOA->AFR[1] &= ~(1 << 28);// alternate function pa15 bcz af1 0001
	GPIOA->AFR[1] &= ~(1 << 29);
	GPIOA->AFR[1] &= ~(1 << 30);
	GPIOA->AFR[1] &= ~(1 << 31);
	GPIOA->AFR[1] |= (1 << 28);

	RCC->APB1ENR = (1<<0);
	TIM2->CR1 &=~(1<<0);
	TIM2->SMCR |= (7<<6); // manual ts 205
	TIM2->SMCR |= (1<<14);// manual ece timer led
	TIM2->CR1 |= (1<<0);

	while(1){
		lcd(0x80,0);
		lcd_string("Count is ");
		lcd(0x89,0);
		single_print(TIM2->CNT);
	}

}
int main(void)
{
	lcd_gpio_init();
	lcd_init();
	counter_init();
}
