/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t *rcc_ahb1enr=(uint32_t*)0x40023830;// for setting the bits
uint32_t *gpiob_moder_led = (uint32_t*)0x40020400;  // GPIOB mode register
uint32_t *gpiob_moder_switch = (uint32_t*)0x40020400;  // GPIOB mode register
uint32_t *gpiob_odr = (uint32_t*)0x40020414;
uint32_t *gpiob_idr = (uint32_t*)0x40020410; /// switch1 input data regsiter

int main(void)
{
		*rcc_ahb1enr |= (1 << 1);  // port b
		// Clear bits 26 and 27 to 00
			*gpiob_moder_led |=(1<< 26);  // This clears both bits 26 and 27 for PB13

			// Set bits 26 and 27 to 01 for output mode
			*gpiob_moder_led &=~(1<< 27);

		// Clear bits 28 and 29 to 00
				*gpiob_moder_led &= ~(1<< 29);  // This clears both bits 26 and 27 for PB13

				// Set bits 28 and 29 to 01 for output mode
				*gpiob_moder_led |= (1<< 28);


	// Clear bits
		*gpiob_moder_switch&=~(3<< 6);// this clear 6th bits// switch as 00 bcz going for 00 will go 11 which is 3
		*gpiob_moder_switch &=~(3<< 8);// this clear 8th bits// switch as 00 bcz going for 00 will go 11 which is 3

					while(1)
					{
	                   uint32_t buttonstatus2=(uint32_t)(*gpiob_idr &(1<<3));
	                   uint32_t buttonstatus3=(uint32_t)(*gpiob_idr &(1<<4));
	                   if(buttonstatus2 == 0)// switch active low pb7
						{
	                	   *gpiob_odr &=~(1<<13);//led on

						}
	                   else if(buttonstatus3 == 0)
					   {
	                	   *gpiob_odr &=~(1 << 14); //set pb13
					   }

	                   else{
	                	   *gpiob_odr|=(1<<13);//led off
	                       *gpiob_odr|=(1<<14);//led off
	                	   }
					}
}
