/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t *rcc_ahb1enr=(uint32_t*)0x40023830;// for setting the bits
uint32_t *gpiob_moder = (uint32_t*)0x40020400;  // GPIOB mode register
uint32_t *gpiob_odr = (uint32_t*)0x40020414;

int main(void)
{
	/* Loop forever */
		  *rcc_ahb1enr |= (1 << 1);  // Enable GPIOB clock necessary

		// Clear bits 28 and 29 to 00
		*gpiob_moder &= ~(1<< 28);  // This clears both bits 26 and 27 for PB13

		// Set bits 28 and 29 to 01 for output mode
		*gpiob_moder |= (1<< 29);


		while(1)
		{

			*gpiob_odr &= ~(1 << 14); //set pb13 to low
			for(unsigned int i=0;i<100000;i++);
			*gpiob_odr |= (1 << 14); //off
			for(unsigned int i=0;i<100000;i++);


		}

}
